name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  get:

    steps:
    - uses: actions/checkout@v1
    - uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: 2.088.0
    - name: Test
      run: dub test
