name: Build
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup dmd  
      uses: mihails-strasuns/setup-dlang@v0.5.0
      with:
          compiler: dmd-2.076.1
    - name: Checkout
      uses: actions/checkout@v1
    - name: Running the script
      run: |
        chmod +x ./script.sh
        ./script.sh

  # compile:
  #   needs: build
  #   name: Compile
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Compiling
  #     shell: bash
  #     run: |
  #       cd ..
  #       git branch