name: dmd
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0.3.0
      with:
        dmd-version: 2.088.0

  compile:
    needs: build
    name: Compile
    runs-on: ubuntu-latest
    steps:

    - name: Compiling
      shell: bash
      run: |
        locate hello.d