name: Build
on:
  workflow_dispatch:
  push:
    branches: 
      - master
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup dmd  
      uses: dlang-community/setup-dlang@v1
      with:
          compiler: dmd-2.076.1
    - name: Checkout
      uses: actions/checkout@v1
    - name: Running the script
      run: |
        chmod +x ./script.sh
        ./script.sh
    - name: Enabling 2MB HugePages
        run: |
          sudo sysctl -w vm.nr_hugepages=4
          cat /sys/kernel/mm/hugepages/hugepages-2048kB/free_hugepages

  # compile:
  #   needs: build
  #   name: Compile
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Compiling
  #     shell: bash
  #     run: |
  #       cd ..
  #       git branch
